apiVersion: v1
kind: Service
metadata:
    name: proyectofinal-service
    namespace: proyectofinal-namespace
spec:
    selector:
        app: proyectofinal-deployment
    ports:
        - protocol: TCP
          port: 7000
          targetPort: 7000
